version: "2.4"

services:
  app:
    extends:
      file: build-app.yaml
      service: app
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "video"
    environment:
      DOCKER_BUILDKIT: 0
