version: "2.4"

services:
  app:
    extends:
      file: build-app.yaml
      service: app
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "video"
    logging:
      driver: "json-file"
      options:
        max-file: "10"   # number of files or file count
        max-size: "100m" # file size
