version: "2.4"

services:
  pip-compiler:
    extends:
      file: pip-compiler.yaml
      service: pip-compiler
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - "video"
