version: "2.4"

services:
  app:
    extends:
      file: build-app.yaml
      service: app
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      UPLOAD_TO_GITHUB: "${UPLOAD_TO_GITHUB}"
    group_add:
      - "video"
    volumes:
      - "../build/pytorch:/tmp/pytorch"
