version: "2.4"

services:
  demo-ai-learns-playing-sonic:
    image: "${APP_NAME}:${VERSION}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'echo ready || exit 1'" ]
      interval: 10s
      timeout: 10s
      retries: 120

  integration-tests:
    build:
      context: "../tests/integration-tests"
    environment:
      IN_REQUIREMENTS: "${IN_REQUIREMENTS:-requirements.in}"
      PYTEST_ADDOPTS: "${PYTEST_ADDOPTS:-}"
      PYTHONPATH: "src"
    volumes:
      - "../tests/integration-tests:/usr/src/integration-tests"
