version: "3.4"

services:
  pip-compiler:
    build:
      context: ../docker-files/pip-compiler
    environment:
      IN_REQUIREMENTS: "${IN_REQUIREMENTS:-requirements.in}"
      SRC_APP: "${SRC_APP}"
    volumes:
      - "../${SRC_APP}:/usr/src/app"
