version: "2.4"

services:
  pip-compiler:
    build:
      context: ../docker-files/pip-compiler
    environment:
      IN_REQUIREMENTS: "${IN_REQUIREMENTS}"
      SRC_DIR: "${SRC_DIR}"
    volumes:
      - "../src/${SRC_DIR}:/usr/src/source"
