version: "2.4"

services:
  app:
    image: "${APP_NAME}:${VERSION}"
    environment:
      DISPLAY: "$DISPLAY"
      UPLOAD_TO_ARTIFACTORY: "${UPLOAD_TO_ARTIFACTORY}"
    group_add:
      - "video"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "../build/pytorch:/app/src/build/pytorch"
