version: "2.4"

services:
  app:
    image: "${APP_NAME}:${VERSION}"
    environment:
      DISPLAY: "$DISPLAY"
    devices:
      - "/dev/dri"
    group_add:
      - "video"
    volumes:
      - "${ROM_PATH}:/tmp/roms"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
