version: "2.4"

services:
  app:
    image: "${APP_NAME}:${VERSION}"
    environment:
      DISPLAY: "$DISPLAY"
    group_add:
      - "video"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      # For testing and building PyTorch and deploy it to a Python wheel artifactory repository
      # - "../build:/usr/src"
