image: ubuntu:20.04

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install apt-utils pkg-config software-properties-common gnupg
  - DEBIAN_FRONTEND=noninteractive apt-get -y install apt-transport-https ca-certificates curl lsb-release
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - DEBIAN_FRONTEND=noninteractive apt-get install -y make
  - docker-compose --version
  - docker system prune -af
  - df -ih

stages:
  - validate
  - build base ubuntu image
  - release pytorch rocm pypi package

validates_docker_compose_files:
  stage: validate
  variables:
    BUILD_ARGUMENT: "validate-docker-compose-files"
    SRC_APP: "src/demo"
  script:
    - make -f MakefilePyTorch ${BUILD_ARGUMENT}

build_base_ubuntu_2004_image:
  stage: build base ubuntu image
  variables:
    ROCM_ARCH: "gfx803"
    ROCM_VERSION: "5.1.3"
    APP_NAME: "base-ubuntu-2004"
    BUILD_ARGUMENT: "build-app"
    SRC_APP: "docker-files/base-ubuntu-2004"
  script:
    - make -f MakefilePyTorch ${BUILD_ARGUMENT}

package_and_release_pytorch_pypi_package:
  stage: release pytorch rocm pypi package
  variables:
    ROCM_ARCH: "gfx803"
    ROCM_VERSION: "5.1.3"
    APP_NAME: "amd-rocm-pytorch-release"
    BUILD_ARGUMENT: "build-app"
    SRC_APP: "docker-files/amd-pytorch-release"
  script:
    - make -f MakefilePyTorch ${BUILD_ARGUMENT}
