name: "Python CI pipeline"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y build-essential
      - name: update hello-world python dependencies
        env:
          BUILD_ARGUMENT: "update-app-requirements"
          IN_REQUIREMENTS: "${IN_REQUIREMENTS}"
          SRC_APP: "${SRC_APP}"
        run: docker-compose -f docker-compose-files/pip-compiler.yaml run --rm pip-compiler
