name: "Python CI pipeline"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y build-essential
      - name: update hello-world python dependencies
        env:
          BUILD_ARGUMENT: "update-app-requirements"
          IN_REQUIREMENTS: "requirements.in"
          SRC_APP: "hello-world"
        run: make "${BUILD_ARGUMENT}"
