name: "Python CI pipeline"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y build-essential
      - name: Validate Docker-Compose files
        env:
          BUILD_ARGUMENT: "validate-docker-compose-files"
          SRC_APP: "src/test"
        run: make "${BUILD_ARGUMENT}"
      - name: Update hello-world Python dependencies
        env:
          BUILD_ARGUMENT: "update-app-requirements"
          IN_REQUIREMENTS: "requirements.in"
          SRC_APP: "src/hello-world"
        run: make "${BUILD_ARGUMENT}"
      - name: Update unit tests Python dependencies
        env:
          BUILD_ARGUMENT: "update-unit-tests-requirements"
          IN_REQUIREMENTS: "requirements.in"
          SRC_APP: "tests/unit-tests"
        run: make "${BUILD_ARGUMENT}"
      - name: Run unit tests
        env:
          BUILD_ARGUMENT: "unit-tests"
          IN_REQUIREMENTS: "requirements.in"
          SRC_APP: "src/demo/hello_world"
        run: make "${BUILD_ARGUMENT}"
