name: "Python CI pipeline"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: compile
        env:
          BUILD_ARGUMENT: "build"
        run: docker-compose -f docker-compose-files/builder.yaml run arch-builder
